version: '3'

services:

  note_app:
    container_name: note_app
    restart: always
    build: ./note_app
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 wsgi:app


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - note_app